WITH CTE AS (

select     
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)),

CASE
when DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
then 'Weekend'
else 'BUSINESSDAY'
end as  DAY_TYPE
from 
{{ source('demo', 'bike') }}

)

select * from CTE